### ISSUE TITLE
Construct Notebook DS: Saving, Loading

### ISSUE THREAD

**Issue by KuraideWolfie** [ECU-CSCI-4230/SpiralBound#5]
Construct functions **toString()** and **fromString(str)** that will, respectively, save information about a notebook, and parse information about a notebook, to/from String representations. toString() should be applicable to any instance of the classes, and fromString(...) should be static - that is, it takes a String and returns an instance of the class after data has been loaded. Functions **save(dir)** and **load(dir)** should also be made to save and load book information, and stored in the Book class.

**Tasks**:
- [x] toString() and fromString(...) for Book
- [x] toString() and fromString(...) for Section
- [x] toString() and fromString(...) for Page
- [x] toString() and fromString(...) for Block
- [ ] save(...) and load(...) in Book

The string provided to save(...)/load(...) will be a directory name that stores information about a book in the following form:

+ Parent directory (book name)
--- Book file (**.bk** file extension)
--+ Section directory (01, for example)
----- Section file (**.sec** file extension)
----- Page file (**.pg** file extension)

**Comment by KuraideWolfie** [comment]
Closing this because save()/load() will not be important in the Notebook API. These functions will be handled in the main window source.
